default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: root
  password: tiger
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  port: 5433

development:
  <<: *default
  database: tiger_development

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
